'''
Made By UTS
'''
import os
import sys
os.system("rm version.txt")
os.system("rm log.db")
os.system("rm sql.db")
os.system("rm html1.txt")
os.system("rm html2.txt")
os.system("rm main_com.py")
os.system("rm index_com.py")
os.system("rm main_txt.py")
os.system("rm index.db")
os.system("rm -rf __pycache__")
#os.system("rm theme_main.py")
os.system("rm main_txt.py")
os.system("rm theme_write.py")
os.system("rm page1.txt")
os.system("rm page2.txt")
os.system("rm index.py")
os.system("rm index.html")
os.system("rm -rf css")
os.system("rm -rf js")
os.system("rm -rf images")
os.system("rm -rf img")
os.system("rm -rf fonts")
os.system("rm -rf image")
os.system("rm -rf font")
os.system("clear")
print("+++++ClearAll-PyBlog!+++++")
print("+++++++Made By UTS+++++++")
print("Github@underthestars-zhy/PyBlog")
print("==========================================")
sys.exit()